#!/bin/bash

DIRECTION=$1
EXTENSION=$2
BACKUPDIR=$3
ARCHIVENAME=$4
FILEINDEX=0
CURRENT="$(pwd)"

mkdir -p $BACKUPDIR

FILES=$(find $DIRECTION -name "*.$EXTENSION")

for FILE in $FILES
do
	FILENAME=$(basename $FILE)
	CLEARFILENAME="${FILENAME%.*}"
        cp "$FILE" "$CURRENT/$BACKUPDIR"
	mv "$CURRENT/$BACKUPDIR/$FILENAME" "$CURRENT/$BACKUPDIR/$CLEARFILENAME-$FILEINDEX.$EXTENSION"
	FILEINDEX=$((FILEINDEX+1))

done

tar -czf $ARCHIVENAME $BACKUPDIR
echo "done"
