name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
  workflow_dispatch:
 
jobs:
  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v2
 
      - name: Build
        run: |
          cd task5 && mkdir 3rdparty && git clone https://github.com/google/googletest.git 3rdparty &&
          mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=../install .. && make && make install
 
      - name: Test
        uses: akhtyamovpavel/ActionGtestReport@v0.0.9
        with:
          report-path: report.xml
          working-directory: task5/
          exec-path: bin/CTestExe
 
 
      - name: UploadArtifacts
        uses: actions/upload-artifact@v2
        with:
          name: Distributive
          path: task5/install/exe/*name: progtech-task5-ci

on:
  push:
    branches: [ task5 ]
  pull_request:
    branches: 
      -master

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: |
          cd task5
          mkdir 3rdparty
          sudo apt-get install libgtest-dev
          cp -r /usr/src/gtest/* ./3rdparty
          mkdir build
          cd build
          cmake ..
          make
          sudo make install
          
      - name: Test
        uses: akhtyamovpavel/ActionGtestReport@v0.0.9
        with:
          exec-path: bin/CTestExe
          report-path: report.xml
          working-directory: task5/
          
      - name: UploadArtifacts
        uses: actions/upload-artifact@v2
        with:
          name: Distributive
          path: |
            task5/bin
            task5/lib
