# This is a basic workflow to help you get started with Actions
 
name: CI
 
# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
 
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
 
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
 
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
 
      # Runs a single command using the runners shell
      - name: Build
        run: |
          mkdir 3rdparty && git clone https://github.com/google/googletest.git 3rdparty && cd task5
          mkdir build && cd build && cmake -DCMAKE_INSTALL_PREFIX=../install .. && make && make install
 
      - name: Test
        uses: akhtyamovpavel/ActionGtestReport@v0.0.9
        with:
          report-path: report.xml
          working-directory: task5/
          exec-path: bin/CTestExe
 
 
      - name: UploadArtifacts
        uses: actions/upload-artifact@v2
        with:
          name: Distributive
          path: task5/install/exe/*
